In [2]:
print("Hello")

Hello


In [57]:
pwd()

'/Users/amankumar/Desktop/Work/Trainings/Data Science and ML/Day 1'

In [4]:
dir("pd")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

## Imports


In [5]:
import pandas as pd
import platform
import sys
import os
import calendar
import numpy as np
import functools

In [6]:
pd.DataFrame({'A': {"one": 1, "two": 2}})

A
one  1
two  2

In [7]:
a = 1
b = 12 + 3j
print(a +  b)

(13+3j)


In [8]:
print(platform.python_version())

3.11.7


In [9]:
prime_numbers = [2,3,5,7,11,13,17,19,23]
names = ['John', 'Ana', 'Rich', 'Drake']
emp = ['Rita', 'female', 23, 4.5, 4500]
temp = [23, 23, 24, 25, 28, 28, 29, 28, 27, 26, 25, 23]

In [10]:
print(type("aman"))
print(sorted(names))
print(set(temp))

<class 'str'>
['Ana', 'Drake', 'John', 'Rich']
{23, 24, 25, 26, 27, 28, 29}


In [11]:
marks = int(input("Enter marks:"))
if marks >= 90:
    print("A")
elif marks >= 75 and marks < 90:
    print("B")
elif marks >= 55 and marks < 75:
    print("C")
elif marks >= 35 and marks < 55:
    print("D")
else:
    print("E")

A


In [12]:
for num in range(1,101):
    if num % 6 == 0:
        print(num, end=" ")
print()

6 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 


In [13]:
word = "Skill Sigma"
word2 = "TSE"
print(word + word2)
print(word2 * 5)
print(word[2:6])
print("Sigma" in word)
print("Sigma" not in word)
print(r'c://Python')
print("wording format is %s"%word)
print(len(word))
print(word.capitalize())
print(word2.isupper())
print(word.istitle())
print("{} {}".format(word,word2))
l = 10
b = 20
print("{} {}".format(l,b))
print(word.count('l'))
print(word.find('g'))
print(word.split(" "))

Skill SigmaTSE
TSETSETSETSETSE
ill 
True
False
c://Python
wording format is Skill Sigma
11
Skill sigma
True
True
Skill Sigma TSE
10 20
2
8
['Skill', 'Sigma']


In [14]:
calendar.calendar(2012,2,1,6)

'                                  2012\n\n      January                   February                   March\nMo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su\n                   1             1  2  3  4  5                1  2  3  4\n 2  3  4  5  6  7  8       6  7  8  9 10 11 12       5  6  7  8  9 10 11\n 9 10 11 12 13 14 15      13 14 15 16 17 18 19      12 13 14 15 16 17 18\n16 17 18 19 20 21 22      20 21 22 23 24 25 26      19 20 21 22 23 24 25\n23 24 25 26 27 28 29      27 28 29                  26 27 28 29 30 31\n30 31\n\n       April                      May                       June\nMo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su\n                   1          1  2  3  4  5  6                   1  2  3\n 2  3  4  5  6  7  8       7  8  9 10 11 12 13       4  5  6  7  8  9 10\n 9 10 11 12 13 14 15      14 15 16 17 18 19 20      11 12 13 14 15 16 17\n16 17 18 19 20 21 22      21 22 23 24 25 26 27      18 19 20 21 22 23 24\n23 24

In [15]:
print((lambda x,y: x+y)(2,3))
nums = [10,20,30,40]
for i, num in enumerate(nums):
    nums[i] = 2 * num
print(nums)

# using lambda
print(list(map(lambda x: x * 2, nums)))

# filter(lambda exp, list)
words = ["abc", "2e", "", "jrkefmd"]
print(list(filter(None, words)))

# lambda
print(functools.reduce(lambda x,y : x + y, nums))

5
[20, 40, 60, 80]
[40, 80, 120, 160]
['abc', '2e', 'jrkefmd']
200


In [16]:
a = np.array([1,2,3])
b = np.array([5,6,7])

c = np.arange(5,50,5, dtype=int)
print(c)


[ 5 10 15 20 25 30 35 40 45]


In [17]:
heights = np.array([1.23, 1.65, 1.55, 1.87])
weights = np.array([])

In [18]:
a = np.array([1,2,3,4,5], ndmin = 2)
print(a, a.shape)
a = np.array([[1,2,3], [5,6,7]])
print(a, a.shape)
print(a.ndim)

[[1 2 3 4 5]] (1, 5)
[[1 2 3]
 [5 6 7]] (2, 3)
2


In [19]:
a = np.array([[1,2], [3, 4]])
b = np.array([[5,6], [7,8]])

print(a + b)
print(a - b)
print(a.prod())
print(a.sum())
print(a.cumsum())

randos = np.random.randint(1,20,(2,5))
print(randos)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
24
10
[ 1  3  6 10]
[[19  6 11 11 16]
 [ 4  3  6 19  8]]


In [20]:
np.random.seed(25)
r_arr = np.random.random((3,5))
print(r_arr)

[[0.87012414 0.58227693 0.27883894 0.18591123 0.41110013]
 [0.11737555 0.68496874 0.43761106 0.55622933 0.36708032]
 [0.40236573 0.1130407  0.44703085 0.58544512 0.1619851 ]]


## Pandas
* Axis = 0 --> Row-wise operations
* Axis = 1 --> Col-wise operations

In [27]:
sample_data = pd.read_csv('Sample_data.csv')
matches = pd.read_csv('Day1_Oracle_Training/matches.csv')
print(sample_data.head())
print(sample_data.shape)

    ID  Gender  Race  SEB  School  Prog  Read  Write  Math1  Math2  SST
0   70       0     4    1       1     1    57     52     41     47   57
1  121       1     4    2       1     3    68     59     53     63   61
2   86       0     4    3       1     1    44     33     54     58   31
3  141       0     4    3       1     3    63     44     47     53   56
4  172       0     4    2       1     2    47     52     57     53   61
(200, 11)


In [ ]:
print(matches.head())

In [43]:
# it means we want to sum for all rows of the columns from Read .. SST both inclusive
sample_data['Total'] = sample_data.loc[:,'Read': 'SST'].sum(axis = 1)


In [44]:
sample_data.head()

ID  Female  Race  SEB  School  Prog  Read  Write  Math1  Math2  SST  Total
0   70       0     4    1       1     1    57     52     41     47   57    254
1  121       1     4    2       1     3    68     59     53     63   61    304
2   86       0     4    3       1     1    44     33     54     58   31    220
3  141       0     4    3       1     3    63     44     47     53   56    263
4  172       0     4    2       1     2    47     52     57     53   61    270

In [45]:
sample_data.rename({'Female': 'Gender'}, axis=1, inplace=True)

In [46]:
sample_data.head()

ID  Gender  Race  SEB  School  Prog  Read  Write  Math1  Math2  SST  Total
0   70       0     4    1       1     1    57     52     41     47   57    254
1  121       1     4    2       1     3    68     59     53     63   61    304
2   86       0     4    3       1     1    44     33     54     58   31    220
3  141       0     4    3       1     3    63     44     47     53   56    263
4  172       0     4    2       1     2    47     52     57     53   61    270

In [81]:
sd1 = sample_data.loc[1:10, ["ID", "Read", "Write"]]
sd2 = sample_data.loc[50:75, ["ID", "Read", "Prog"]]
sd1

ID  Read  Write
1   121    68     59
2    86    44     33
3   141    63     44
4   172    47     52
5   113    44     52
6    50    50     59
7    11    34     46
8    84    63     57
9    48    57     55
10   75    60     46

In [ ]:
sd1 = pd.concat([sd1, sd2], axis=1, join="outer")
sd1

In [ ]:
sample_data.insert(len(sample_data.columns), "Percentage", sample_data.Total/500 * 100)

In [59]:
sample_data.head()

ID  Gender  Race  SEB  School  Prog  Read  Write  Math1  Math2  SST  \
0   70       0     4    1       1     1    57     52     41     47   57   
1  121       1     4    2       1     3    68     59     53     63   61   
2   86       0     4    3       1     1    44     33     54     58   31   
3  141       0     4    3       1     3    63     44     47     53   56   
4  172       0     4    2       1     2    47     52     57     53   61   

   Total  Percentage  
0    254        50.8  
1    304        60.8  
2    220        44.0  
3    263        52.6  
4    270        54.0

In [87]:
data = {
    'country' : ['Brazil' , 'Russia', 'India','China', 'South Africa'],
    'capitals' : ['Brasilia', 'Moscow', 'Delhi', 'Beijing','Pretoria'],
    'area' : [8.516, 17.1, 3.286, 9.597, 1.221],
    'population' : [200.4, 143.5, 1252, 1357, 52.98] 
    }
brics = pd.DataFrame(data,columns= list(data.keys()), index = ["A",'B','C','D','E'])
brics

country  capitals    area  population
A        Brazil  Brasilia   8.516      200.40
B        Russia    Moscow  17.100      143.50
C         India     Delhi   3.286     1252.00
D         China   Beijing   9.597     1357.00
E  South Africa  Pretoria   1.221       52.98

In [89]:
brics_dup = pd.concat([brics, brics[:3]])
brics_dup.duplicated()

A    False
B    False
C    False
D    False
E    False
A     True
B     True
C     True
dtype: bool

In [98]:
print(brics.columns)
brics.sort_values('area', inplace=True, axis=0, ascending=True)
brics

Index(['country', 'capitals', 'area', 'population'], dtype='object')


country  capitals    area  population
E  South Africa  Pretoria   1.221       52.98
C         India     Delhi   3.286     1252.00
A        Brazil  Brasilia   8.516      200.40
D         China   Beijing   9.597     1357.00
B        Russia    Moscow  17.100      143.50

In [104]:
marks = pd.read_csv("Class_marks.csv")
pers = pd.read_csv("Class_pers.csv")
print(marks.head())
print(pers.head())

  Enrol No.  Maths  Science  English
0      A101     16       15       12
1      A102     16       17       11
2      A103     12       18       17
3      A104     11       13       16
4      A105     11       10       15
  Enrol No.    Name Gender  Age Address Interest
0      A101  George      M   10    abcd    music
1      A102  Monica      F   11     cds    music
2      A103  Jennie      F   11     wes    dance
3      A104   Baley      M   12     adf   sports
4      A105  Garret      M   10      as   sports


In [103]:
marks2 = marks.assign(Name = pers.Name)
marks2

Enrol No.  Maths  Science  English     Name
0       A101     16       15       12   George
1       A102     16       17       11   Monica
2       A103     12       18       17   Jennie
3       A104     11       13       16    Baley
4       A105     11       10       15   Garret
5       A106     10       18       14   Warren
6       A107     14       14       11    Janet
7       A108     19       15       12     John
8       A109     19       11       13    Maria
9       A110     16       13       18     Sean
10      A111     15       13       14  Cynthia
11      A112     16       17       19     Rita
12      A113     13       19       10    Maria
13      A114     12       19       17      Leo
14      A115     18       19       17    Keith
15      A116     12       20       17   Nicole
16      A117     10       18       11     Dave
17      A118     11       17       10     Fred
18      A119     15       19       12    Annie
19      A120     19       19       20    Frank