In [1]:
#import quad from integrate subpackage
from scipy.integrate import quad

In [2]:
#define function for integration of x
def integrateFunction(x):
    return x

In [3]:
#perform quad integration for function of x for limit 0 to 1
quad(integrateFunction,0,1)

(0.5, 5.551115123125783e-15)

In [4]:
#define function for ax + b
def integrateFn(x,a,b):
    return x*a+b

In [5]:
#Declare value of a and b
a=3
b=2

In [6]:
#perform quad integration and pass function and arguments
quad(integrateFn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

In [7]:
#Import integrate package and sub-package
import scipy.integrate as integrate

In [8]:
#Define function for x + y
def f(x,y):
    return x + y
integrate.dblquad(f,0,1,lambda x: 0,lambda x:2)
#perform multiple integration using the lambda built-in function

(3.0, 4.436070580899685e-14)

In [9]:
#SciPy Sub-package: Optimization
#Optimization is a process to improve performance of a system mathematically 
#by fine tuning the process parameters.
#SciPy provides several optimization algorithms such as bfgs,Nelder-Meda simplex,
#Newton Conjugate Gradient,COBYLA, or SLSQP


In [10]:
import numpy as np
from scipy import optimize

In [11]:
dir('Scipy')

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [12]:
#Define function for x^2 + 5 sin x
def f(x):
    return x**2 + 5*np.sin(x)

In [13]:
#perform optimize minimize function using bfgs method and options
minimaValue = optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [14]:
#perform optimize minimize function using bfgs method and without options
minimaValueWithoutOpt = optimize.minimize(f,x0=2,method='bfgs')

In [15]:
minimaValueWithoutOpt

      fun: -3.2463942726915214
 hess_inv: array([[0.15445818]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [16]:
import numpy as np
from scipy.optimize import root
def rootfunc(x):
    return x + 3.5 * np.cos(x)

In [17]:
#pass x value in the argument for root
rootValue = root(rootfunc,0.3)

In [18]:
##Function values and array values
rootValue

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

In [19]:
##Scipy provides rapid linerar algebra capabilities and contains advanced algebraic functions
#This function is used to compute the inverse of the given matrix
#Lets take a look at the inverse matrix
##Import linalg and define a numpy matrix or array

import numpy as np
from scipy import linalg
matrix=np.array([[10,6],[2,7]])

In [20]:
matrix

array([[10,  6],
       [ 2,  7]])

In [21]:
#view the type
type(matrix)

numpy.ndarray

In [22]:
#use inv function to inverse the matrix
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [23]:
##With this function you can compute the value of the determinant for the given matrix
##Import linalg and define an numpy matrix or array
import numpy as np
from scipy import linalg
matrix=np.array([[4,9],[3,5]])
matrix


array([[4, 9],
       [3, 5]])

In [24]:
#Use det function to find the determinant value of the matrix
linalg.det(matrix)

-7.000000000000001

In [25]:
'''
Linear systems
linear equations
2x+3y+z=21
-x+5y_4z=9
3x+2y+9z=6.solve(numArray)
'''

import numpy as np
from scipy import linalg
numArray=np.array([[2,3,1],[-1,5,4],[3,2,9]])
numArrValue=np.array([21,9,6])
linalg.solve(numArray,numArrValue)  ##use solve method

array([ 4.95,  4.35, -1.95])

In [26]:
##single value decomposition(svd)

import numpy as np
from scipy import linalg
numSvdArr=np.array([[3,5,1],[9,5,7]])   ##define matrix
numSvdArr.shape  ##Find shape of ndarray which is 2 by 3 matrix
linalg.svd(numSvdArr)

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [27]:
'''

(array([[-0.37879831,  0.92547925],    ##unitary matrix
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),    ##Sigma or square root of eigenvalues
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],  ##VH is values collected into unitary matrix
        [-0.68041382,  0.27216553,  0.68041382]]))

SyntaxError: EOF while scanning triple-quoted string literal (871062011.py, line 8)

In [28]:
##Handle Missing Values
##Its difficult to operate on a dataset when it has missing values
##or uncommon indices

In [29]:
import pandas as pd
#declare first series
first_series=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

#declare second series
second_series=pd.Series([10,20,30,40,50],index=['c','e','f','g','h'])
sum_of_series=first_series + second_series

In [30]:
sum_of_series

a     NaN
b     NaN
c    13.0
d     NaN
e    25.0
f     NaN
g     NaN
h     NaN
dtype: float64

In [31]:
#drop NaN(not a Number) values from dataset
dropna_s = sum_of_series.dropna()

In [32]:
dropna_s

c    13.0
e    25.0
dtype: float64

In [33]:
##Handling Missing Values with Functions
##fill values with zeros before performing addition operation for missing indices
fill_NaN_with_Zeros_before_sum=first_series.add(second_series,fill_value=0)

In [34]:
fill_NaN_with_Zeros_before_sum

a     1.0
b     2.0
c    13.0
d     4.0
e    25.0
f    30.0
g    40.0
h    50.0
dtype: float64

In [35]:
##Data Operation
##Data operation can be performed through various built-in methods for faster data processing

import pandas as pd

In [36]:
#declare movie rating dataframe : rating from 1 to 5 (star * rating)
df_movie_rating=pd.DataFrame(
                {'movie 1': [4,5,3,3,2,1],
                'movie 2': [4,5,2,3,4,2]},
                index=['Tom','Jeff','Peter','Ram','Ted','Paul']
)

In [37]:
df_movie_rating

movie 1  movie 2
Tom          4        4
Jeff         5        5
Peter        3        2
Ram          3        3
Ted          2        4
Paul         1        2

In [38]:
##Data Operation with Functions

#while peforming data operation, custom functions can be applied with the applymap method

def movie_grade(rating):
    if rating==5:
        return 'A'
    if rating==4:
        return 'B'
    if rating==3:
        return 'C'
    else:
        return 'F'
    

In [39]:
print(movie_grade(5))

A


In [40]:
df_movie_rating.applymap(movie_grade)

movie 1 movie 2
Tom         B       B
Jeff        A       A
Peter       C       F
Ram         C       C
Ted         F       B
Paul        F       F

In [41]:
###Data operations with Statistical functions
import pandas as pd
df_test_scores=pd.DataFrame(
                {'Test1': [95,84,73,88,82,61],
                'Test2': [74,85,82,73,77,79]},
                index=['Jack','Lewis','Patrick','Rich','Kelly','Pauls']
)

In [42]:
#Apply max function to find the maximum score
df_test_scores.max()

Test1    95
Test2    85
dtype: int64

In [43]:
#Apply the mean function to fid the average score
df_test_scores.std()

Test1    11.979149
Test2     4.633213
dtype: float64

In [44]:
#Apply the std function to find the standard deviation for both the tests
df_test_scores.mean()

Test1    80.500000
Test2    78.333333
dtype: float64

In [45]:
#Data operations using Group by
df_president_name=pd.DataFrame({'first':['George','Bill','Ronald','Jimmy','George'],
                               'last':['Bush','Clinton','Regan','Carter','Washington']})


In [46]:
grouped=df_president_name.groupby('first')

In [47]:
grp_data=grouped.get_group('George')

In [48]:
grp_data

first        last
0  George        Bush
4  George  Washington

In [49]:
df_president_name.sort_values('first')

first        last
1    Bill     Clinton
0  George        Bush
4  George  Washington
3   Jimmy      Carter
2  Ronald       Regan

In [50]:
#Data Standardization:
#Create a function to return the standardize value
def standardize_tests(test):
    return(test-test.mean())/test.std()

In [51]:
standardize_tests(df_test_scores['Test1'])

Jack       1.210437
Lewis      0.292174
Patrick   -0.626088
Rich       0.626088
Kelly      0.125218
Pauls     -1.627829
Name: Test1, dtype: float64

In [52]:
#Apply the function to the entire dataset
def standardize_test_scores(datafrm):
    return datafrm.apply(standardize_tests)


In [53]:
#Standardized test data is applied for the entire DataFrame
standardize_test_scores(df_test_scores)

Test1     Test2
Jack     1.210437 -0.935276
Lewis    0.292174  1.438886
Patrick -0.626088  0.791387
Rich     0.626088 -1.151109
Kelly    0.125218 -0.287777
Pauls   -1.627829  0.143889

In [54]:
##Data Standardization:
#Normalize the data attributes for iris dataset
from sklearn.datasets import load_iris
from sklearn import preprocessing

In [55]:
#load the iris dataset
iris=load_iris()

In [56]:
print(iris.data.shape)

(150, 4)


In [57]:
#separate the data from the target attributes
x=iris.data
y=iris.target

In [58]:
#normalize the data attributes


In [59]:
##It is a good programming practice to rescale data before training an ML Algorithm. 
##With rescaling, data units are eliminated allowing you to easily compare data 
##from different locations
normalized_X=preprocessing.scale(x)

In [60]:
print(normalized_X)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [61]:
##Data scaling Feature scaling is also very important when values of each feature
##in a dataset vary between random values

data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))

In [62]:
##Normalize the dataset

from sklearn.datasets import load_iris
from sklearn import preprocessing
iris=load_iris()

In [63]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [64]:
x=iris.data
y=iris.target

In [65]:
normalized_X=preprocessing.scale(x)

In [66]:
print(normalized_X)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [67]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import Normalizer
data =read_csv('d:/diabetes.csv')

In [68]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [69]:
array=data.values

In [70]:
Data_normalizer = Normalizer().fit(array)

In [71]:
Data_normalized = Data_normalizer.transform(array)

In [72]:
Data_normalized

array([[0.03355185, 0.82761219, 0.40262215, ..., 0.00350617, 0.27959871,
        0.00559197],
       [0.008424  , 0.71604034, 0.55598426, ..., 0.00295683, 0.26114412,
        0.        ],
       [0.04039717, 0.9240852 , 0.32317734, ..., 0.00339336, 0.16158867,
        0.00504965],
       ...,
       [0.02691539, 0.65135243, 0.38758161, ..., 0.00131885, 0.16149234,
        0.        ],
       [0.00665291, 0.83826692, 0.39917472, ..., 0.00232187, 0.31268687,
        0.00665291],
       [0.00791454, 0.73605211, 0.55401772, ..., 0.00249308, 0.18203439,
        0.        ]])

In [73]:

from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import Binarizer

In [74]:
data =read_csv('d:/diabetes.csv')

In [75]:
array=data.values

In [76]:
binarizer=Binarizer(threshold=0.5).fit(array)

In [77]:

Data_binarized=binarizer.transform(array)

In [78]:
Data_binarized

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 0.],
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 0.]])

In [79]:
##Data Labeling
import numpy as np
from sklearn import preprocessing
input_labels = ['justice','patience','justice','truth','patience','loyalty','perseverance']
encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)
test_labels = ['truth','justice','patience','loyalty']
encoded_values=encoder.transform(test_labels)
print(test_labels)
encoded_values=[2,0,4,3]
decoded_list=encoder.inverse_transform(encoded_values)
print(encoded_values)
print(list(decoded_list))


['truth', 'justice', 'patience', 'loyalty']
[2, 0, 4, 3]
['patience', 'justice', 'truth', 'perseverance']


In [80]:
## data feature selection

In [81]:
##Supervised learning
'''
knn
regression - simple regression,multiple regression,logistic regression
kernel SVM
Navie bayes
support Vector machine
decision tree classification
Random forest
'''

'\nknn\nregression - simple regression,multiple regression,logistic regression\nkernel SVM\nNavie bayes\nsupport Vector machine\ndecision tree classification\nRandom forest\n'

In [82]:
'''
unsupervised learning
clustering
association rule learning - market basket analysis
Natural language processing

Deep learning

dimensionality reduction

Reinforcement learning
'''



'\nunsupervised learning\nclustering\nassociation rule learning - market basket analysis\nNatural language processing\n\nDeep learning\n\ndimensionality reduction\n\nReinforcement learning\n'